name: Evals CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-evals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Add step to install dependencies if solvers need any
      # - name: Install requirements
      #   run: |
      #     pip install -r requirements.txt || echo "No requirements file"
      - name: Run docstring solver stub
        run: python solvers/docstring_solver.py .
      - name: Run ARC42 solver stub
        run: python solvers/arc42_solver.py .
      # Add steps for other solvers as they are created
